### PR TITLE
moved view-edit buttons in front

### PR DESCRIPTION
**Pull request by inemp**
view-edit buttons are now on front.

### CODE REVIEW

**Comment by cyt-mn** [comment]
Technically this is working. However, I'd leave the buttons on the right, as all other views have it like that (and it is a common paradigm). I'd prefer to exclude columns and only remain:
ID | Lab Code | Department | Institution | City

What are your thoughts @Cornelieke-GenDx and @espierin ? Removing columns, or buttons upfront?

image

**Comment by espierin** [comment]
I would favor to limit the columns for ease of navigation. Yet, please check that everything becomes available when clicking the edit button.

Kind regards,

Eric Spierings

.

------------------------------------------------------------------------------

De informatie opgenomen in dit bericht kan vertrouwelijk zijn en is
uitsluitend bestemd voor de geadresseerde. Indien u dit bericht onterecht
ontvangt, wordt u verzocht de inhoud niet te gebruiken en de afzender direct
te informeren door het bericht te retourneren. Het Universitair Medisch
Centrum Utrecht is een publiekrechtelijke rechtspersoon in de zin van de W.H.W.
(Wet Hoger Onderwijs en Wetenschappelijk Onderzoek) en staat geregistreerd bij
de Kamer van Koophandel voor Midden-Nederland onder nr. 30244197.

Denk s.v.p aan het milieu voor u deze e-mail afdrukt.

------------------------------------------------------------------------------

This message may contain confidential information and is intended exclusively
for the addressee. If you receive this message unintentionally, please do not
use the contents but notify the sender immediately by return e-mail. University
Medical Center Utrecht is a legal person by public law and is registered at
the Chamber of Commerce for Midden-Nederland under no. 30244197.

Please consider the environment before printing this e-mail.

**Comment by Cornelieke-GenDx** [comment]
I agree with Eric. 
Let's go for fewer columns on the Labs page, so you do not need to horizontally scroll to see the buttons on the right. As long as all the lab details are visible on the edit and view pages, this will work perfectly.

**Comment by inemp** [comment]
Which attributes do we want to be showing of all? I propose all until "state".

**Comment by FPR-GenDx** [comment]
Follow Mathias'lead, Five columns

**Comment by inemp** [comment]
Done!

**Pull request closed without merging**
